version: '3.7'
services:
  db:
    image: mysql:5.7
    container_name: ghost_db
    volumes:
     - /tmp/data/mysql:/var/lib/mysql
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: sehr_geheim
     MYSQL_USER: ghost
     MYSQL_PASSWORD: secret
     MYSQL_DATABASE: ghost
  web:
    depends_on:
     - db
    image: ghost:1-alpine
    container_name: ghost_web
    ports:
     - "8082:2368"
    restart: always
    environment:
      base__client: mysql
      database__connection__host: ghost_mysql
      database__connection__user: ghost
      database__connection__password: secret
      database__connection__database: ghost
